[WIP] Add support for Uniffi
input-output-hk/sd-jwt-rust pull request #1
Opened 2024-03-11 13:40 UTC by FabioPinheiro

2024-03-13 00:44 UTC, hamada147 commented on output-frameworks/demo-scala/native-lib/NATIVE/linux-x86-64/libuniffi_sd_jwt.so
Please don't merge while the compiled version exist

2024-03-21 09:24 UTC, goncalo-frade-iohk requested changes

2024-03-21 09:24 UTC, goncalo-frade-iohk commented on src/disclosure.rs
> +#[derive(Debug, Clone)]
Mate unfortunately this is something we cannot do. For maintainability issues.

We want to be able to merge with updates they do, so we cannot change the source code. Rather we need to make wrappers around it as needed, on our Uniffi project.

PS: The comment is here but it applies to any change in this folder.

2024-03-27 08:14 UTC, mkbreuningIOHK commented
@hamada147 , can you add the reference ATL-6717 in the PR comment?

2024-05-02 11:26 UTC, FabioPinheiro commented on output-frameworks/demo-scala/native-lib/NATIVE/linux-x86-64/libuniffi_sd_jwt.so
Let's not commit the binaries

2024-05-02 11:26 UTC, FabioPinheiro commented on output-frameworks/demo-scala/sd-jwt-jvm-1.0-SNAPSHOT.jar
Same here.Let's not commit the binaries

2024-05-02 11:28 UTC, hamada147 commented on output-frameworks/demo-scala/sd-jwt-jvm-1.0-SNAPSHOT.jar
Commit by mistake, gonna do a rebase and delete them

2024-05-02 11:28 UTC, hamada147 commented on output-frameworks/demo-scala/native-lib/NATIVE/linux-x86-64/libuniffi_sd_jwt.so
Commit by mistake, gonna do a rebase and delete them

2024-05-02 14:56 UTC, Dale-iohk commented
![Logo](https://cdn.ast.checkmarx.net/integrations/logo/Checkmarx.png)
**Checkmarx One – Scan Summary & Details** – [24f43833\-958c\-4376\-8cea\-a83ec0d632b3](https://eu.ast.checkmarx.net/projects/5d4491d1-a62b-45db-b93c-b978026ab8e7/scans?id=24f43833-958c-4376-8cea-a83ec0d632b3&branch=uniffi)
### No New Or Fixed Issues Found

2024-05-03 15:45 UTC, FabioPinheiro commented
The force push to the branch is a bit inconvenient

2024-05-03 15:53 UTC, FabioPinheiro commented on Cargo.toml
> +name = "sd_jwt_rs"
In Java this import is not convenient.
`import sd_jwt_rs.*`

Let`s pick another name without camel case or underscores

2024-05-13 10:17 UTC, FabioPinheiro commented
We should add to the README the command you are using to build, +- as I had before.

2024-05-13 10:17 UTC, FabioPinheiro reviewed
I want
 to test the Jar but LGTM

2024-05-27 15:51 UTC, goncalo-frade-iohk approved these changes

2024-05-27 15:52 UTC, mineme0110 approved these changes

2024-05-27 15:57 UTC, merged